siteName: Bascule Site
dateFormat: dd/MM/yyyy
dateTimeFormat: HH:mm:ss dd/MM/yyyy
author: bascule
theme: {{themeName}}
tagskey: tags
postsPerPage: 2

directories:
  source: sources
  output: site
  assets: assets
  templates: templates
plugins: []
processors: [IndexPageGenerator,PostNavigationGenerator,TaxonomyNavigationGenerator,org.liamjd.bascule.lib.generators.pdf.SinglePagePDFGenerator]
